# default apps
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# path
#export PATH=~/.local/bin:~/.local/bin/npm-global/bin:$PATH

# cleaning up home folder
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export N_PREFIX="$HOME/.local/bin/n"
#export ZDOTDIR="$HOME/.config/zsh"
#export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
#export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel

# lf icons
# export LF_ICONS= "\
# ln      \
# or      \
# tw      t\
# ow      \
# st      t\
# di      \
# pi      p\
# so      s\
# bd      b\
# cd      c\
# su      u\
# sg      g\
# ex      \
# fi      \
# *.styl          \
# *.sass          \
# *.scss          \
# *.htm           \
# *.html          \
# *.slim          \
# *.haml          \
# *.ejs           \
# *.css           \
# *.less          \
# *.md            \
# *.mdx           \
# *.markdown      \
# *.rmd           \
# *.json          \
# *.webmanifest   \
# *.js            \
# *.mjs           \
# *.jsx           \
# *.rb            \
# *.gemspec       \
# *.rake          \
# *.php           \
# *.py            \
# *.pyc           \
# *.pyo           \
# *.pyd           \
# *.coffee        \
# *.mustache      \
# *.hbs           \
# *.conf          \
# *.ini           \
# *.yml           \
# *.yaml          \
# *.toml          \
# *.bat           \
# *.mk            \
# *.jpg           \
# *.jpeg          \
# *.bmp           \
# *.png           \
# *.webp          \
# *.gif           \
# *.ico           \
# *.twig          \
# *.cpp           \
# *.c++           \
# *.cxx           \
# *.cc            \
# *.cp            \
# *.c             \
# *.cs            󰌛\
# *.h             \
# *.hh            \
# *.hpp           \
# *.hxx           \
# *.hs            \
# *.lhs           \
# *.nix           \
# *.lua           \
# *.java          \
# *.sh            \
# *.fish          \
# *.bash          \
# *.zsh           \
# *.ksh           \
# *.csh           \
# *.awk           \
# *.ps1           \
# *.ml            λ\
# *.mli           λ\
# *.diff          \
# *.db            \
# *.sql           \
# *.dump          \
# *.clj           \
# *.cljc          \
# *.cljs          \
# *.edn           \
# *.scala         \
# *.go            \
# *.dart          \
# *.xul           \
# *.sln           \
# *.suo           \
# *.pl            \
# *.pm            \
# *.t             \
# *.rss           \
# '*.f#'          \
# *.fsscript      \
# *.fsx           \
# *.fs            \
# *.fsi           \
# *.rs            \
# *.rlib          \
# *.d             \
# *.erl           \
# *.hrl           \
# *.ex            \
# *.exs           \
# *.eex           \
# *.leex          \
# *.heex          \
# *.vim           \
# *.ai            \
# *.psd           \
# *.psb           \
# *.ts            \
# *.tsx           \
# *.jl            \
# *.pp            \
# *.vue           \
# *.elm           \
# *.swift         \
# *.xcplayground  \
# *.tex           󰙩\
# *.r             󰟔\
# *.rproj         󰗆\
# *.sol           󰡪\
# *.pem           \
# *gruntfile.coffee       \
# *gruntfile.js           \
# *gruntfile.ls           \
# *gulpfile.coffee        \
# *gulpfile.js            \
# *gulpfile.ls            \
# *mix.lock               \
# *dropbox                \
# *.ds_store              \
# *.gitconfig             \
# *.gitignore             \
# *.gitattributes         \
# *.gitlab-ci.yml         \
# *.bashrc                \
# *.zshrc                 \
# *.zshenv                \
# *.zprofile              \
# *.vimrc                 \
# *.gvimrc                \
# *_vimrc                 \
# *_gvimrc                \
# *.bashprofile           \
# *favicon.ico            \
# *license                \
# *node_modules           \
# *react.jsx              \
# *procfile               \
# *dockerfile             \
# *docker-compose.yml     \
# *docker-compose.yaml    \
# *compose.yml            \
# *compose.yaml           \
# *rakefile               \
# *config.ru              \
# *gemfile                \
# *makefile               \
# *cmakelists.txt         \
# *robots.txt             󰚩\
# *Gruntfile.coffee       \
# *Gruntfile.js           \
# *Gruntfile.ls           \
# *Gulpfile.coffee        \
# *Gulpfile.js            \
# *Gulpfile.ls            \
# *Dropbox                \
# *.DS_Store              \
# *LICENSE                \
# *React.jsx              \
# *Procfile               \
# *Dockerfile             \
# *Docker-compose.yml     \
# *Docker-compose.yaml    \
# *Rakefile               \
# *Gemfile                \
# *Makefile               \
# *CMakeLists.txt         \
# *jquery.min.js          \
# *angular.min.js         \
# *backbone.min.js        \
# *require.min.js         \
# *materialize.min.js     \
# *materialize.min.css    \
# *mootools.min.js        \
# *vimrc                  \
# Vagrantfile             \
# *.tar   \
# *.tgz   \
# *.arc   \
# *.arj   \
# *.taz   \
# *.lha   \
# *.lz4   \
# *.lzh   \
# *.lzma  \
# *.tlz   \
# *.txz   \
# *.tzo   \
# *.t7z   \
# *.zip   \
# *.z     \
# *.dz    \
# *.gz    \
# *.lrz   \
# *.lz    \
# *.lzo   \
# *.xz    \
# *.zst   \
# *.tzst  \
# *.bz2   \
# *.bz    \
# *.tbz   \
# *.tbz2  \
# *.tz    \
# *.deb   \
# *.rpm   \
# *.jar   \
# *.war   \
# *.ear   \
# *.sar   \
# *.rar   \
# *.alz   \
# *.ace   \
# *.zoo   \
# *.cpio  \
# *.7z    \
# *.rz    \
# *.cab   \
# *.wim   \
# *.swm   \
# *.dwm   \
# *.esd   \
# *.jpg   \
# *.jpeg  \
# *.mjpg  \
# *.mjpeg \
# *.gif   \
# *.bmp   \
# *.pbm   \
# *.pgm   \
# *.ppm   \
# *.tga   \
# *.xbm   \
# *.xpm   \
# *.tif   \
# *.tiff  \
# *.png   \
# *.svg   \
# *.svgz  \
# *.mng   \
# *.pcx   \
# *.mov   \
# *.mpg   \
# *.mpeg  \
# *.m2v   \
# *.mkv   \
# *.webm  \
# *.ogm   \
# *.mp4   \
# *.m4v   \
# *.mp4v  \
# *.vob   \
# *.qt    \
# *.nuv   \
# *.wmv   \
# *.asf   \
# *.rm    \
# *.rmvb  \
# *.flc   \
# *.avi   \
# *.fli   \
# *.flv   \
# *.gl    \
# *.dl    \
# *.xcf   \
# *.xwd   \
# *.yuv   \
# *.cgm   \
# *.emf   \
# *.ogv   \
# *.ogx   \
# *.aac   \
# *.au    \
# *.flac  \
# *.m4a   \
# *.mid   \
# *.midi  \
# *.mka   \
# *.mp3   \
# *.mpc   \
# *.ogg   \
# *.ra    \
# *.wav   \
# *.oga   \
# *.opus  \
# *.spx   \
# *.xspf  \
# *.pdf   \
# "
export LC_ALL=fr_FR.UTF-8 