#! /bin/bash

# Resizing screen
xandr -S 1920x1080 &

# autostart
bash $HOME/.config/bspwm/scripts/autostart.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8'
# xidlehook --timer 5 '/usr/bin/betterlockscreen' '' &

bspc config border_width         	3
bspc config window_gap          	4

bspc config focused_border_color "#00ffbf"
bspc config normal_border_color "#ff44ab"

bspc config split_ratio          	0.52
bspc config single_monocle 	 	true
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false

bspc config focus_follow_pointer 	true
bspc config pointer_folows_focus 	false
bspc config pointer_motion_interval 	5
bspc config pointer_modifier 		mod4
bspc config pointer_action1		move 
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Alacritty state=floating rectangle=853x600+80+50 follow=on private=true
# bspc rule -a Pavucontrol state=floating
# bspc rule -a Thunar state=floating center=true rectangle=700x700 private=true
# bspc rule -a *:*:"Code - OSS" state=floating rectangle=900x900+300+100 follow=on private=true
bspc rule -a "*" state=floating
